import type { Icon } from '@phosphor-icons/react'
import {
  ForkKnife, Coffee, BeerBottle, Wine, CookingPot, Cake, BowlFood,
  AirplaneTilt, Car, Train, Bus, Boat, Tent, MapTrifold, SuitcaseRolling, Bed,
  Barbell, PersonSimpleRun, Bicycle, SwimmingPool, Heart, FirstAidKit, Pill,
  Basketball, SoccerBall, TennisBall,
  Briefcase, PresentationChart, VideoCamera, Users, Chats, EnvelopeSimple,
  Phone, DesktopTower, Handshake,
  GraduationCap, BookOpen, Exam, ChalkboardTeacher, Student, Notebook,
  MusicNotes, Ticket, FilmSlate, Television, GameController, MicrophoneStage,
  PaintBrush, Camera, Confetti,
  ShoppingCart, Scissors, Package, Wrench,
  House, Baby, Dog, Tree,
  Church, Cross, StarOfDavid,
  Bank, Money, Scales, Receipt,
  Code, Robot, Flask,
  Gift, Champagne, HeartHalf, FlowerLotus,
  CalendarDots, Clock, Megaphone, FlagBanner,
} from '@phosphor-icons/react'

/** Maps backend kebab-case icon names to Phosphor React components. */
export const ICON_MAP: Record<string, Icon> = {
  // Food & Dining
  'fork-knife': ForkKnife,
  'coffee': Coffee,
  'beer-bottle': BeerBottle,
  'wine': Wine,
  'cooking-pot': CookingPot,
  'cake': Cake,
  'bowl-food': BowlFood,
  // Travel & Transportation
  'airplane-tilt': AirplaneTilt,
  'car': Car,
  'train': Train,
  'bus': Bus,
  'boat': Boat,
  'tent': Tent,
  'map-trifold': MapTrifold,
  'suitcase-rolling': SuitcaseRolling,
  'bed': Bed,
  // Fitness & Health
  'barbell': Barbell,
  'person-simple-run': PersonSimpleRun,
  'bicycle': Bicycle,
  'swimming-pool': SwimmingPool,
  'heart': Heart,
  'first-aid-kit': FirstAidKit,
  'pill': Pill,
  'basketball': Basketball,
  'soccer-ball': SoccerBall,
  'tennis-ball': TennisBall,
  // Work & Office
  'briefcase': Briefcase,
  'presentation-chart': PresentationChart,
  'video-camera': VideoCamera,
  'users': Users,
  'chats': Chats,
  'envelope-simple': EnvelopeSimple,
  'phone': Phone,
  'desktop-tower': DesktopTower,
  'handshake': Handshake,
  // Education
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  'exam': Exam,
  'chalkboard-teacher': ChalkboardTeacher,
  'student': Student,
  'notebook': Notebook,
  // Entertainment & Social
  'music-notes': MusicNotes,
  'ticket': Ticket,
  'film-slate': FilmSlate,
  'television': Television,
  'game-controller': GameController,
  'microphone-stage': MicrophoneStage,
  'paint-brush': PaintBrush,
  'camera': Camera,
  'confetti': Confetti,
  // Shopping & Errands
  'shopping-cart': ShoppingCart,
  'scissors': Scissors,
  'package': Package,
  'wrench': Wrench,
  // Home & Family
  'house': House,
  'baby': Baby,
  'dog': Dog,
  'tree': Tree,
  // Religion & Spirituality
  'church': Church,
  'cross': Cross,
  'star-of-david': StarOfDavid,
  // Finance & Legal
  'bank': Bank,
  'money': Money,
  'scales': Scales,
  'receipt': Receipt,
  // Tech & Science
  'code': Code,
  'robot': Robot,
  'flask': Flask,
  // Celebration & Milestones
  'gift': Gift,
  'champagne': Champagne,
  'heart-half': HeartHalf,
  'flower-lotus': FlowerLotus,
  // Miscellaneous
  'calendar-dots': CalendarDots,
  'clock': Clock,
  'megaphone': Megaphone,
  'flag-banner': FlagBanner,
}
